config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup'    => 'users#new'
  resources :users do
    member do
      post  'reactivate'         # Resends the activation email.
      patch 'update_description' # Posts title & description.
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, "About Us" %>
<article class="article">
  <h1 hidden>StartThis: About Us</h1>
  <section>
    <h2>About StartThis.org</h2>
    <p>
      I started learning programming systematically in 2016, and I was wondering
      what to do for my first serious Rails project--something not too hard.
      So I thought: "Why not make that 'free ideas' blog, but soup it up with
      the ability to like, comment on, and even organize participation in these
      ideas?"
      So I says to meself, I says, "Meself, that's a damn good idea.
      A damn good idea!"
    </p>
    <p>
      So what you see here is a simple website in which you can judge, comment
      on, and sign up to help with these ideas.
      You can also submit a new idea!
      But, sorry in advance, but I'll only post ideas I think are awesome, and
      I can be kind of harsh when it comes to judging ideas, so don't be hurt
      please.
      The bar is high.
    </p>
    <p>
      The site is pretty simple. Explore different ideas.
      Upvote as many as you like. The ones people like the most rise to the top.
    </p>
    <p>
      So what are the corkers? What are the duds?
    </p>
    <p>
      Then the really fun part happens.
    </p>
    <p>
      What I'm trying to do is to give everyone a place where they can judge
      these ideas and, if they're excited enough about them, actually help
      bring them into existence.
    </p>
    <p>
      You can also get involved.
      If you're a potential user, we have a button for you to press.
      There are also buttons to press if you want to work on a project; if you've
      actually started a project and want help; if you're a distinguished expert
      who wants to advise (I'll be the judge of that; you really will have to be
      distinguished in your field); and more.
      You'll get a different fun inspirational message whenever you press one
      of these buttons. Try it!
    </p>
    <p>
      This platform is for non-profit, open source projects.
      I don't have time to lead these projects, but if I think you're doing
      good, credible work, I'll give you as much help as my limited (currently,
      very limited) time permits.
      I'm not rich and can't offer monetary support, but I have some connections
      and can advise you.
      I won't insist on owning the intellectual property if you're doing all
      the work and I'm just advising you.
      In other words, if you're just executing my idea, I'll ask for bragging
      rights, but dude, it's your project!
    </p>
    <p>
     I'm excited about this project project!
     Let's make some awesome stuff and change the world!
    </p>
    <p>
      Larry Sanger
    </p>
  </section>
  <div class="login_button center">
    <%= link_to "Join!", new_user_path, class: "btn btn-lg btn-primary" %>
  </div>
</article>

app/views/static_pages/help.html.erb
<% provide :title, "Help and FAQ" %>
<article class="article">
  <h1 hidden>StartThis: Help and FAQ</h1>
  <section class="help">
    <h2>Help</h2>
    <p>When the website is ready, you'll find links to help pages here.</p>
  </section>
  <section class="faq">
    <h2>FAQ</h2>
    <p class="question">When will this website be ready?</p>
    <p class="answer">We might have a decent first draft by early
    2018.</p>

    <p class="question">Why aren't there any ideas on the site yet?</p>
    <p class="answer">Because Larry hasn't finished going through Hartl's
    Rails tutorial yet. Soon!</p>

    <p class="question">Well, what the heck <em>can</em> I do on this site?</p>
    <p class="answer">You can actually <%= link_to "sign up", signup_path %> and
      activate your account and everything! Whoa nelly!</p>

  </section>
  <div class="login_button center">
    <%= link_to "Join!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</article>

app/views/static_pages/home.html.erb
<% provide :title, "Free ideas to change the world" %>
<article class="article">
  <div class="home_page_article_header">
    <h1>StartThis.org</h1>
    <p>
      Come on&#151;do it!
    </p><p>
      Like you, I've had many more exciting ideas than I can possibly execute
      myself.
      I've decided to share mine with the world.
      If they excite you, please use them with my compliments.
      You can contribute your own, too.<br>
      <div class="text-right">&#151;<%= link_to "Larry Sanger",
                                  User.find_by(email:
                                  "yo.larrysanger@gmail.com") %></div>
    </p>
  </div>
  <section class="introductory_text">
    <h2>You in?</h2>

    <p>Ideas are cheap. Execution is everything.</p>
    <p>
      I've had lots of interesting ideas over the years, many of which
      I've gotten quite excited and passionate about, and a few of which I've
      actually executed.
      They've really started to pile up, and I know I'll never be able to start
      them all myself.
      Moreover, these are all ideas for nonprofit, open source projects.
    </p>
    <p>
      One of my ideas is to start a blog in which I just give away all these
      free ideas.
      So that's what I'm doing now. <%= link_to "Read more...", about_path %>
    </p>
  </section>
  <div class="login_button center">
    <%= link_to "Join!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</article>