config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup'    => 'users#new'
  resources :users do
    member do
      post  'reactivate'         # Resends the activation email.
      patch 'update_description' # Posts title & description.
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  name              :string
#  email             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  password_digest   :string
#  remember_digest   :string
#  admin             :boolean          default(FALSE)
#  activation_digest :string
#  activated         :boolean          default(FALSE)
#  activated_at      :datetime
#  reset_digest      :string
#  reset_sent_at     :datetime
#  title             :string
#  description       :text
#

class User < ActiveRecord::Base
  has_many :messages, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.\+]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i   # used to check that input email is hip to the groove
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6,
                                 message: "must have at least 6 characters"},
                       on: create
  validates :title, length: { maximum: 255 }
  validates :description, length: { maximum: 13_000 } # ~2000 words
  default_scope -> { order(created_at: :desc) }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token (for logging the user in securely, in persistent sessions).
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    digest_of_token = User.digest(remember_token)
    update_attribute(:remember_digest, digest_of_token)
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user, i.e., deletes his digest so he can't use his token anymore.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    # Opens mailer, creates an #account_activation email, delivers it.
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Converts email to all-lowercase.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token (N.B.!) and digest.
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :update_description]
  before_action :correct_user,   only: [:edit, :update, :update_description]
  before_action :admin_user,     only: :destroy
  def new
    @user = User.new
  end

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    unless @user.activated?
      flash[:danger] = "Sorry, #{@user.name}'s account has not been activated."
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account. Allow
        a minute or two."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Another one bites the dust!"
    redirect_to users_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Resends activation email. This has its own 'reactivate' route (see
  # routes.rb) and the route is followed only via a link, contained in an error
  # flash, found at sessions_controller.rb.
  def reactivate
    @user = User.find(params[:id])
    @user.create_activation_digest
    @user.update_attribute(:activation_digest, @user.activation_digest)
    @user.send_activation_email
    flash[:info] = "Click the activation link we just emailed you,
                    and we'll log you in."
    redirect_to root_url
  end

  # Handles user's posted title and description.
  def update_description
    @user = User.find(params[:id])
    # For smart message, first check if user had a title.
    old_title = @user.title
    # For smart message, first check if user had a description.
    old_desc = @user.description
    if title_desc_params[:title]
      # And clear out any bad titles.
      session[:bad_title] = nil
      # Save title, if present.
      if title_desc_params[:title].present?
        # Attempt to save; if failed, flash with warning.
        begin
          @user.update_attributes!(title: title_desc_params[:title])
        rescue ActiveRecord::RecordInvalid
          flash[:warning] = "Unable to save. (Too long?)"
          session[:bad_title] = title_desc_params[:title]
        end
      elsif old_title
        @user.update_attributes!(title: nil)
        flash[:info] = "Title deleted."
      end
    end
    if title_desc_params[:description]
      # And clear out any bad descriptions.
      session[:bad_desc] = nil
      # Save description, if present.
      if title_desc_params[:description].present?
        # Attempt to save; if failed, flash with warning.
        begin
          @user.update_attributes!(description: title_desc_params[:description])
        rescue ActiveRecord::RecordInvalid
          flash[:warning] = "Unable to save. (Too long?)"
          session[:bad_desc] = title_desc_params[:description]
        end
      elsif old_desc
        @user.update_attributes!(description: nil)
        flash[:info] = "Description deleted."
      end
    end
    # Same logic as before, now for description.
    # Make sure two different [:success] flashes work! Probably not!
    redirect_to "/users/#{@user.id}"
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a user is in fact logged in.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms a user is in fact the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms that a user is an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def title_desc_params
      params.require(:user).permit(:title, :description)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Fiddle with contents of error messages (e.g., toss dups).
  def massage_error_messages(messages)
    messages = messages.uniq
  end

end # of UsersHelper

app/views/users/_user.html.erb
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                       data: { confirm: "You sure?" } %>
      <% end %>
      <% if user.title %>
        <br>
        <span class="index-title">
          <%= user.title %>
          <% if user.description %>
            <%= link_to "[more...]", user_path(user) %>
          <% end %>
        </span>
      <% end %>
    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'layouts/form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Member list") %>
<h1>The ideators</h1>

<%= will_paginate %>

<ol class="users">
  <% # See _user.html.erb %>
  <%= render @users %>
</ol>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Create a New StartThis Account") %>
<% provide(:button_text, 'Create my account') %>
<article>
  <h1>Create a New StartThis Account</h1>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'layouts/form'  %>
    </div>
  </div>
</article>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<!-- Name and Gravatar, in <aside> -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user, size: 80) %>
        <%= @user.name %>
      </h1>
      <br>Joined: <%= @user.created_at.strftime("%B %d, %Y") %>
    </section>
  </aside>

  <!-- Title and Description -->
  <div class="title_desc col-md-8">

    <!-- Title span -->
    <% if current_user == @user %>
    <%
      # If no title yet, show grey link, which activates a JS method that
      # displays an edit form. If there is a title, show it with an edit
      # pencil.
      # Always load this initially hidden span, whether or not used -->
      # Display to user when opened -->
    %>
      <span id="edit_user_title" %>
        <%= form_for(@user, url: update_description_user_path,
                     method: :patch) do |f| %>
          <span class="input_buttons">
            <%= button_tag "", type: 'submit',
                               class: "glyphicon glyphicon-ok" %>
          </span>
          <span class="input_field">
            <%= f.text_field :title, class: 'form-control title_input' %>
          </span>
        <% end %>
      </span>
      <% if @user.title %>
        <!-- Display user title to user -->
        <h2 class="user_title">
          <span class="glyphicon glyphicon-pencil"></span>
          <span id="user_title_text"><%= @user.title %></span>
        </h2>
      <% else %>
        <h2 class="user_title">
          <span id="user_title_text" class="italics silver">
            Click to add profile title</span>
          <span class="glyphicon glyphicon-plus silver"></span>
        </h2>
      <% end %>
    <% elsif current_user != @user %>
      <% if @user.title %>
        <!-- Display user title to other user -->
        <h2 class="user_title_other_user">
          <span class="user_title_text"><%= @user.title %></span>
        </h2>
      <% end %>
    <% end %>

    <!-- Description span -->
    <% if current_user == @user %>
      <!-- Always load this initially hidden span, whether or not used -->
      <!-- Display to user when opened -->
      <span id="edit_user_desc" %>
        <%= form_for(@user, url: update_description_user_path,
                     method: :patch) do |f| %>
          <span class="input_buttons">
            <%= button_tag "", type: 'submit',
                               class: "glyphicon glyphicon-ok" %>
          </span>
          <span class="input_field">
            <%= f.text_area :description,
                             class: 'form-control desc_input' %>
          </span>
          <span class="formatting_link">
            <%= link_to "formatting help",
            "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet",
            target: "_blank", class: "formatting_link" %>
          </span>
        <% end %>
      </span>
      <% if @user.description %>
        <!-- Display user title to user -->
        <div class="user_desc">
          <span class="glyphicon glyphicon-play"></span>
          <span class="glyphicon glyphicon-pencil"></span>
          <div id="user_desc_text"><%= markdown(@user.description) %></div>
        </div>
      <% else %>
        <div class="user_desc">
          <span id="user_desc_text" class="italics silver">
            Introduce yourself</span>
          <span class="glyphicon glyphicon-plus silver"></span>
        </div>
      <% end %>
    <% elsif current_user != @user %>
      <% if @user.description %>
        <!-- Display user description to other user -->
        <div class="user_desc_other_user">
          <span class="glyphicon glyphicon-play"></span>
          <div class="user_desc_text"><%= markdown(@user.description) %></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>