config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup'    => 'users#new'
  resources :users do
    member do
      post  'reactivate'         # Resends the activation email.
      patch 'update_description' # Posts title & description.
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <%= link_to image_tag("rails_logo.png", alt: "Powered by Rails", 
                  class: "rails_logo"), 'http://rubyonrails.org/' %>
      <small>Copyright &#169; <%= Time.new.year %> Larry Sanger</small>
    </footer>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Retype password" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">

          <!-- Hamburger ################################################## -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target="#linkage">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Logo ##################################################### -->
            <div class="logo">
              <%= link_to "<span class='top'>Start</span><br>
              <span class='larger bottom'>This!</span>".html_safe, root_path %>
            </div>

            <!-- Tagline ################################################## -->
            <div class="tagline">
              <div>
                Free ideas to change the world.
                <span class="extra"><br>By Wikipedia’s co-founder and friends.
                  </span>
                <span class="youin">You in?</span>
              </div>
            </div>
          </div>

          <!-- Links ###################################################### -->
          <div class="collapse navbar-collapse" id="linkage">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Help and FAQ", help_path %></li>
              <li><%= link_to "About Us", about_path %></li>
              <% if logged_in? %>
                <li><%= link_to "Members", users_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.name %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings",
                                    edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out",
                                    logout_path, method: "delete" %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
            </ul>
          </div>


        </div>
      </nav>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script  src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message.html_safe,
                        class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>